# the permission message for /skuishy's sub commands
permission-message: "<red>You can not execute this sub-command!"

# whether players with the permission 'skuishy.updatechecker' should be notified if there is an update.
update-checker: true

# whether the plugin should automatically update during shutdown when there is a new version
auto-update: false

# whether a message should be sent whenever a new version check happens.
version-check-msg: true

# elements -----

# whether note elements should be loaded
note-elements: true

# whether permission elements should be loaded
permission-elements: true

# whether plugin elements should be loaded
plugin-elements: true

# whether skin elements should be loaded
skin-elements: true